containers: Fix Smatch fetch
We now need to clone the full repository because this command now failed:
$ git fetch --depth 1 origin 1805d8ab5fb06a176404b52774d124de7f2591ed
error: Server does not allow request for unadvertised object 1805d8ab5fb06a176404b52774d124de7f2591ed

Signed-off-by: Mickaël Salaün <mic@digikod.net>